### ISSUE TITLE
OpenStack - is it intentionally ?

### ISSUE THREAD

**Issue by it-praktyk** [jdauphant/awesome-ansible#21]
The link to project OpenStack directs to [https://github.com/openstack-ansible/openstack-ansible](https://github.com/openstack-ansible/openstack-ansible) when we can read like on the screenshot below.

![screenshot from 2017-09-27 03-36-54](https://user-images.githubusercontent.com/4910261/30891750-29fd42fc-a335-11e7-998c-14c798140e06.png)

Is it intentionally?

**Comment by jdauphant** [comment]
Nope, thanks for the headlight. I fixed it.
