### ISSUE TITLE
Cloud Alchemy

### ISSUE THREAD

**Issue by paulfantom** [jdauphant/awesome-ansible#30]
Would you be interested in including our roles into this list? ([Cloud Alchemy](https://github.com/cloudalchemy)) provides ansible roles to install monitoring solution based on [CNCF](https://cncf.io) projects, currently it installs prometheus and grafana as well as some other things.
Those projects probably could serve as some sort of example since they follow Ansible best practices and have full CI pipelines based on molecule testing framework.
Also there is a repository with [demo site](https://github.com/cloudalchemy/demo-site) which is also provisioned with travis pipeline running every day.

Currently our grafana role is in [official docs](http://docs.grafana.org/administration/provisioning/#configuration-management-tools) and we are trying to include prometheus role into another [official docs](https://github.com/prometheus/prometheus/pull/3505).

I would add PR, but I don't know where to put this :confused:.

**Comment by jdauphant** [comment]
Thanks for your message @paulfantom .
The question is more, would it be interesting for the community ?
I didn't have time to dig into your project that haven't social proof yet.
I will let the community explore it
