### ISSUE TITLE
Add Mitogen for Ansible to the list

### ISSUE THREAD

**Issue by it-praktyk** [jdauphant/awesome-ansible#39]
I read the article [Improving the performance of Ansible](https://www.nexedi.com/blog-Improve.the.performance.of.Ansible) and I've found interesting (but not used) [Mitogen for Ansible](https://mitogen.readthedocs.io/en/latest/ansible.html).

I think that that project is worth to add to the Awesome Ansible list.

CC: @dw

**Comment by jdauphant** [comment]
@it-praktyk Good idea to add Mitogen ! It looks very impressive

**Comment by dw** [comment]
Some [background reading](http://pythonsweetness.tumblr.com/post/171589071872/quadrupling-ansible-performance-with-mitogen) for where this project is heading. Topology-aware file sync should be done in the coming week or two. Thanks for the reference
